name: GitHub Readme YouTube Cards

on:
  schedule:
    - cron: "0 0 * * FRI"  # Cada viernes a medianoche
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Generar tarjetas de YouTube
        uses: DenverCoder1/github-readme-youtube-cards@main
        id: youtube-cards
        with:
          channel_id: UCSu6RatcPG8LXJtHUuAtiTQ
          comment_tag_name: YOUTUBE-CARDS
      - name: Insertar tarjetas en el README.md
        run: |
          echo "${{ steps.youtube-cards.outputs.markdown }}" > cards.md

          # Limpia el bloque anterior
          sed -i '/<!-- BEGIN YOUTUBE-CARDS 
          -->/,/<!-- END YOUTUBE-CARDS -->/c\
          <!-- BEGIN YOUTUBE-CARDS -->\
          <!-- END YOUTUBE-CARDS -->' README.md

          # Inserta las tarjetas
          awk '/<!-- BEGIN YOUTUBE-CARDS -->/
          {print; while((getline line < "cards.md") > 0) 
          print line; found=1; next} /<!-- END 
          YOUTUBE-CARDS -->/{found=0} !found' README.md > tmp.md
          mv tmp.md README.md