name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "0 0 * * FRI"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        id: youtube-cards
        with:
          channel_id: UCSu6RatcPG8LXJtHUuAtiTQ
          comment_tag_name: YOUTUBE-CARDS
      - run: echo OUTPUT '${{ steps.youtube-cards.outputs.markdown }}'
        shell: bash
